// Generated by gencpp from file swarm_aggregation/botPose.msg
// DO NOT EDIT!


#ifndef SWARM_AGGREGATION_MESSAGE_BOTPOSE_H
#define SWARM_AGGREGATION_MESSAGE_BOTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Odometry.h>

namespace swarm_aggregation
{
template <class ContainerAllocator>
struct botPose_
{
  typedef botPose_<ContainerAllocator> Type;

  botPose_()
    : bot_id()
    , botpose()  {
    }
  botPose_(const ContainerAllocator& _alloc)
    : bot_id(_alloc)
    , botpose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _bot_id_type;
  _bot_id_type bot_id;

   typedef std::vector< ::nav_msgs::Odometry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nav_msgs::Odometry_<ContainerAllocator> >> _botpose_type;
  _botpose_type botpose;





  typedef boost::shared_ptr< ::swarm_aggregation::botPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_aggregation::botPose_<ContainerAllocator> const> ConstPtr;

}; // struct botPose_

typedef ::swarm_aggregation::botPose_<std::allocator<void> > botPose;

typedef boost::shared_ptr< ::swarm_aggregation::botPose > botPosePtr;
typedef boost::shared_ptr< ::swarm_aggregation::botPose const> botPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_aggregation::botPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_aggregation::botPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_aggregation::botPose_<ContainerAllocator1> & lhs, const ::swarm_aggregation::botPose_<ContainerAllocator2> & rhs)
{
  return lhs.bot_id == rhs.bot_id &&
    lhs.botpose == rhs.botpose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_aggregation::botPose_<ContainerAllocator1> & lhs, const ::swarm_aggregation::botPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_aggregation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_aggregation::botPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_aggregation::botPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_aggregation::botPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_aggregation::botPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_aggregation::botPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_aggregation::botPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_aggregation::botPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14f9cb1d05d7b333efc6809331fe9a60";
  }

  static const char* value(const ::swarm_aggregation::botPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14f9cb1d05d7b333ULL;
  static const uint64_t static_value2 = 0xefc6809331fe9a60ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_aggregation::botPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_aggregation/botPose";
  }

  static const char* value(const ::swarm_aggregation::botPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_aggregation::botPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] bot_id\n"
"nav_msgs/Odometry[] botpose\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swarm_aggregation::botPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_aggregation::botPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bot_id);
      stream.next(m.botpose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct botPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_aggregation::botPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_aggregation::botPose_<ContainerAllocator>& v)
  {
    s << indent << "bot_id[]" << std::endl;
    for (size_t i = 0; i < v.bot_id.size(); ++i)
    {
      s << indent << "  bot_id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.bot_id[i]);
    }
    s << indent << "botpose[]" << std::endl;
    for (size_t i = 0; i < v.botpose.size(); ++i)
    {
      s << indent << "  botpose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "    ", v.botpose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_AGGREGATION_MESSAGE_BOTPOSE_H
